<?php

declare(strict_types=1);

namespace App\Support\Ledger;

use App\Enums\LedgerEntryType;
use App\Exceptions\CurrencyMismatchException;
use App\Exceptions\InvalidLedgerTransactionException;
use App\Support\Money;
use Illuminate\Support\Str;

/**
 * A balanced set of legs, ready to post (F03).
 *
 * Validated on construction, so an unbalanced, mixed-currency, mis-keyed or
 * self-colliding transaction cannot exist as an object — let alone reach the
 * table. The `transaction_uuid` that groups the legs is *not* here: it is
 * generated by the service at post time, which keeps this object deterministic
 * and I/O-free like the rest of App\Support.
 */
final readonly class LedgerTransaction
{
    /**
     * @param list<LedgerLeg> $legs
     */
    private function __construct(
        public LedgerEntryType $entryType,
        public string $referenceType,
        public int $referenceId,
        public array $legs,
        public string $currency,
    ) {}

    /**
     * @throws InvalidLedgerTransactionException on any broken double-entry rule
     * @throws CurrencyMismatchException         when the legs are not all in one currency
     */
    public static function of(
        LedgerEntryType $entryType,
        string $referenceType,
        int $referenceId,
        LedgerLeg ...$legs,
    ): self {
        $reference = Str::trim($referenceType);

        if ($reference === '') {
            throw InvalidLedgerTransactionException::blankReferenceType();
        }

        if ($referenceId <= 0) {
            throw InvalidLedgerTransactionException::invalidReferenceId($referenceId);
        }

        $legs = array_values($legs);

        if (count($legs) < 2) {
            throw InvalidLedgerTransactionException::tooFewLegs(count($legs));
        }

        $currency = $legs[0]->amount->currency;
        $sum = Money::zero($currency);
        $seen = [];

        foreach ($legs as $leg) {
            // Money::plus raises CurrencyMismatchException, so one currency is enforced by the arithmetic itself.
            $sum = $sum->plus($leg->amount);

            self::assertCorrectlyKeyed($leg);

            if (isset($seen[$leg->accountKey()])) {
                throw InvalidLedgerTransactionException::duplicateAccount($leg->accountType->value, $leg->accountId);
            }

            $seen[$leg->accountKey()] = true;
        }

        if (! $sum->isZero()) {
            throw InvalidLedgerTransactionException::unbalanced($sum->minor, $currency);
        }

        return new self($entryType, $reference, $referenceId, $legs, $currency);
    }

    public function legCount(): int
    {
        return count($this->legs);
    }

    /**
     * A singleton account carries the `account_id = 0` sentinel (R4); every
     * other account is keyed by a real business row. The enum is the single
     * authority for which is which.
     */
    private static function assertCorrectlyKeyed(LedgerLeg $leg): void
    {
        if ($leg->accountType->isSingleton() && $leg->accountId !== 0) {
            throw InvalidLedgerTransactionException::singletonAccountMustUseZero($leg->accountType->value, $leg->accountId);
        }

        if (! $leg->accountType->isSingleton() && $leg->accountId <= 0) {
            throw InvalidLedgerTransactionException::accountRequiresId($leg->accountType->value, $leg->accountId);
        }
    }
}
